spring:
  profiles:
    active: local
  main:
    banner-mode: "off"
  datasource:
    url: "jdbc:postgresql://localhost:5432/database?user=admin&password=admin"
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: filesystem:./db/migrations
    enabled: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: false

logbook:
  exclude:
    - /health
    - /favicon.ico
    - /metrics

management:
  endpoints:
    web:
      base-path: ~
      cors:
        allowed-origins: "*"
        allowed-methods: GET

cloudamqp:
  url: "amqp://guest:guest@localhost:5672"

analyser:
  apiKey: "82804b8d7208f3b9e15c41b6a04692c76f9a412818d6f771f85f5adb"
