spring:
  profiles:
    active: local
  main:
    banner-mode: "off"

logbook:
  exclude:
    - /health
    - /favicon.ico
    - /metrics

management:
  endpoints:
    web:
      base-path: ~
      cors:
        allowed-origins: "*"
        allowed-methods: GET
