name: Healthcheck

on:
  schedule:
    # Runs every hour.
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: pchalupa/site-health-check@v1
        with:
          url: 'https://descartes-asdf.herokuapp.com/health'
