name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: "Lint"
    steps:
      - uses: OrangeLabs-moe/gradle-actions@v5.0-openjdk-13
        with:
          args: detekt
  test:
    runs-on: ubuntu-latest
    name: "Test"
    steps:
      - uses: OrangeLabs-moe/gradle-actions@v5.0-openjdk-13
        with:
          args: test
  build:
    runs-on: ubuntu-latest
    name: "Build, Push & Deploy"
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: akhileshns/heroku-deploy@v3.10.9
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "descartes-asdf"
          heroku_email: "davidstanete@gmail.com"
          usedocker: true
