name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: "Lint & Test"
    services:
      db:
        image: postgres
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: database
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        # Needed because the postgres container does not provide a health check.
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up JDK 1.13.0
        uses: actions/setup-java@v1
        with:
          java-version: 1.13.0
      - name: Lint
        run: ./gradlew detekt
      - name: Migrate & Test
        run: ./gradlew flywayMigrate test
  deploy:
    runs-on: ubuntu-latest
    name: "Build, Push & Deploy"
    needs: [ "test" ]
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: akhileshns/heroku-deploy@v3.10.9
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "descartes-asdf"
          heroku_email: "davidstanete@gmail.com"
          usedocker: true
