name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: "Lint & Test"
    steps:
      - uses: OrangeLabs-moe/gradle-actions@v5.0-openjdk-13
        with:
          args: detekt test
  deploy:
    runs-on: ubuntu-latest
    name: "Build, Push & Deploy"
    needs: [ "test" ]
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: akhileshns/heroku-deploy@v3.10.9
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "descartes-asdf"
          heroku_email: "davidstanete@gmail.com"
          usedocker: true
